add tags to posts
cdlug/cdlug.github.io pull request #29
Opened 2020-03-29 02:26 UTC by haobug

2020-03-29 04:37 UTC, QuantumGhost commented
如果我们要换 Static site generator 的话，还是暂时不要 merge，免得改了再来一次？

2020-03-29 10:41 UTC, TechQuery requested changes

2020-03-29 10:41 UTC, TechQuery commented on _posts/2016-05-25-hello3.md
> +tags: [Hello3,提交文章方法contributing,github在线编辑器github online editor]
```suggestion
tags: 
  - Hello3
  - 提交文章方法
  - contributing
  - github在线编辑器
  - github online editor
```

2020-03-29 10:44 UTC, TechQuery commented
> 如果我们要换 Static site generator 的话，还是暂时不要 merge，免得改了再来一次？

MarkDown 文件头这段 **front-matter 元数据**各家生成器都支持一致的常用字段，可以说是**平台无关**的

2020-03-30 06:04 UTC, too commented
嗯，用 Hugo 的话应该可以自己生成 tags 这些， MD 文件的元数据格式， @TechQuery 给出的挺好的，后面 Hugo 应该也可以采用这个格式吧

2020-03-31 18:29 UTC, TechQuery commented on _posts/2016-05-25-hello3.md
> +tags: [Hello3,提交文章方法contributing,github在线编辑器github online editor]
我在此举例意在“举一反三”，其它数组处也全改为**原生 YAML 语法**

2020-04-04 04:20 UTC, haobug commented on _posts/2016-05-25-hello3.md
> +tags: [Hello3,提交文章方法contributing,github在线编辑器github online editor]
> @haobug 我在此举例意在“举一反三”，其它数组处也全改为**原生 YAML 语法**

都修改了，情merge。

我们约定一个，下次直接 commit 一处，提醒一下 “举一反三”，或者每处都 comment

2020-04-05 15:09 UTC, haobug commented
Need to be revised for Hugo.

https://github.com/cdlug/cdlug.github.io/issues/32

2020-04-06 06:37 UTC, haobug commented
close this
重新修改提交

2020-04-06 09:14 UTC, closed without merging